[project]
name = "quant-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ccxt>=4.5.33",
    "flask>=3.1.2",
    "flask-cors>=6.0.2",
    "numpy>=2.4.1",
    "openai>=2.15.0",
    "pandas>=2.3.3",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
    "schedule>=1.2.2",
    "urllib3>=2.6.3",
]

[project.scripts]
start-bot = "app.main:main"
start-dashboard = "trading_dashboard:main"

[tool.uv]
package = true

[tool.hatch.build.targets.wheel]
packages = ["src/core", "src/app", "trading_bots"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
